/*
Enter your query here.
*/
(
  SELECT CITY, LENGTH(CITY) AS NAME_LENGTH
  FROM STATION
  WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
  ORDER BY CITY ASC
  LIMIT 1
)
UNION
(
  SELECT CITY, LENGTH(CITY) AS NAME_LENGTH
  FROM STATION
  WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
  ORDER BY CITY ASC
  LIMIT 1
);
